version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: tasker-sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fk@71DIy
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
