version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: tasker-sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fk@71DIy
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
volumes:
  mysql-data:
